# -*- coding: utf-8 -*-
"""
Created on Wed Jan 18 18:17:37 2023

@author: Amar Doshi
"""

from FrequencyMap import FrequencyMap


def FrequentWords(Text, k):
    d = FrequencyMap(Text, k)

    maxval = max(d.values())

    return [k for k, v in d.items() if v == maxval]


if __name__ == '__main__':

    # t = "CGATATATCGAT"
    # k = 3

    # t = 'ACGTTGCATGTCGCATGATGCATGAGAGCT'
    # k = 4

    t = 'ATCAATGATCAACGTAAGCTTCTAAGCATGATCAAGGTGCTCACACAGTTTATCCACAACCTGAGTGGATGACATCAAGATAGGTCGTTGTATCTCCTTCCTCTCGTACTCTCATGACCACGGAAAGATGATCAAGAGAGGATGATTTCTTGGCCATATCGCAATGAATACTTGTGACTTGTGCTTCCAATTGACATCTTCAGCGCCATATTGCGCTGGCCAAGGTGACGGAGCGGGATTACGAAAGCATGATCATGGCTGTTGTTCTGTTTATCTTGTTTTGACTGAGACTTGTTAGGATAGACGGTTTTTCATCACTGACTAGCCAAAGCCTTACTCTGCCTGACATCGACCGTAAATTGATAATGAATTTACATGCTTCCGCGACGATTTACCTCTTGATCATCGATCCGATTGAAGATCTTCAATTGTTAATTCTCTTGCCTCGACTCATAGCCATGATGAGCTCTTGATCATGTTTCCTTAACCCTCTATTTTTTACGGAAGAATGATCAAGCTGCTGCTCTTGATCATCGTTTC'
    k = 10

    t = "TAAACGTGAGAGAAACGTGCTGATTACACTTGTTCGTGTGGTAT"
    k = 3


    l = FrequentWords(t, k)

    print()
    print(l)
